[package]
name = "cdcfs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.68"
fastcdc = "3.0.3"
nohash-hasher = "0.2.0"
redis = "0.23.0"
wyhash = "0.5.0"

[dev-dependencies]
dockertest = "0.3.1"
tokio = { version = "1.28.2", features = ["test-util", "macros"] }
tracing = "0.1.13"
tracing-subscriber = "0.2"
test-log = { version = "0.2", default-features = false, features = ["trace"] }
